// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-students.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/env.ts
function requireEnv(name) {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env: ${name}`);
  return v;
}

// src/lib/mcp/tools/list-students.ts
function client(ctx) {
  return createClient(requireEnv("SUPABASE_URL"), requireEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_students_default = defineTool({
  name: "list_students",
  title: "List students",
  description: "List the signed-in user's students, optionally filtered by teacher name.",
  inputSchema: {
    teacher: z.string().nullable().describe("Optional exact teacher name to filter by."),
    limit: z.number().int().min(1).max(500).nullable().describe("Max rows to return. Default 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ teacher, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client(ctx).from("students").select("id,name,teacher,created_at").order("name");
    if (teacher) q = q.eq("teacher", teacher);
    q = q.limit(limit ?? 100);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { students: data } };
  }
});

// src/lib/mcp/tools/list-teachers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(requireEnv("SUPABASE_URL"), requireEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_teachers_default = defineTool2({
  name: "list_teachers",
  title: "List teachers",
  description: "List teachers registered for a given Hijri year.",
  inputSchema: {
    year: z2.string().describe("Hijri year key, e.g. '1446'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client2(ctx).from("teachers").select("id,name,year,created_at").eq("year", year).order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { teachers: data } };
  }
});

// src/lib/mcp/tools/list-teacher-bonuses.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(requireEnv("SUPABASE_URL"), requireEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_teacher_bonuses_default = defineTool3({
  name: "list_teacher_bonuses",
  title: "List teacher bonuses",
  description: "List monthly teacher bonuses (\u0627\u0644\u0625\u0643\u0631\u0627\u0645\u064A\u0627\u062A) for a given Hijri year, optionally filtered by teacher.",
  inputSchema: {
    year: z3.string().describe("Hijri year key, e.g. '1446'."),
    teacher_name: z3.string().nullable().describe("Optional teacher name filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, teacher_name }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client3(ctx).from("teacher_bonuses").select("id,teacher_name,year,month,amount").eq("year", year).order("month");
    if (teacher_name) q = q.eq("teacher_name", teacher_name);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    return { content: [{ type: "text", text: JSON.stringify({ bonuses: data, total }) }], structuredContent: { bonuses: data, total } };
  }
});

// src/lib/mcp/tools/get-student-year-data.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(requireEnv("SUPABASE_URL"), requireEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_student_year_data_default = defineTool4({
  name: "get_student_year_data",
  title: "Get student year data",
  description: "Fetch a student's competition data (grades, hifz, teacher, prize) for a specific Hijri year.",
  inputSchema: {
    student_id: z4.number().int().describe("Student id."),
    year: z4.string().describe("Hijri year key, e.g. '1446'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, year }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client4(ctx).from("year_data").select("*").eq("student_id", student_id).eq("year", year).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { year_data: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hzpvtmfgvddjkuzonict";
var mcp_default = defineMcp({
  name: "ramadan-competition-mcp",
  title: "\u0643\u0634\u0641 \u0627\u0644\u0645\u0633\u0627\u0628\u0642\u0629 \u0627\u0644\u0631\u0645\u0636\u0627\u0646\u064A\u0629 \u2014 MCP",
  version: "0.1.0",
  instructions: "Tools for the Ramadan Quran memorization competition app. Read students, teachers, per-year competition data, and monthly teacher bonuses for the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_students_default, list_teachers_default, list_teacher_bonuses_default, get_student_year_data_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
